toDoSite/rest_app/urls.py
from django.conf import settings
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as auth_token
from . import views

router = DefaultRouter()
router.register('todos', views.TodoViewSet)

app_name = 'rest_app'
urlpatterns = [
    path('', TemplateView.as_view(template_name='rest_app/todo_list_vue.html'), name="rest_index/"),
	path('api/', include(router.urls), name='api'),
    path('token/', auth_token.obtain_auth_token, name='token'),
]

toDoSite/toDoApp/urls.py
from django.urls import path
from . import views #'.' means this directory- '..' would mean parent

app_name = 'toDoApp'
urlpatterns = [
    path('', views.index, name='index'), #app urls are relative to the paths from urls.py at the site level
    path("add/", views.add, name="add"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("mark_done/<int:pk>/", views.mark_done, name="mark_done"),
    path('another_page/', views.another, name='another_page')
]

toDoSite/toDoSite/urls.py
from django.contrib import admin
from django.urls import path, include
from toDoSite import views

# router = routers.DefaultRouter()
# router.register(r'todos', views.TodoViewSet)

urlpatterns = [
    path('', include('toDoApp.urls')), # include('toDoApp.urls') tells this line to go to urls.py at the all level and tack on those paths after the empty string.
    path('rest_index/', include('rest_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),#added to use accounts
    path('accounts/register', views.register, name='register'),
	path('api-auth/', include('rest_framework.urls')),

]

toDoSite/rest_app/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.dispatch import receiver
from django.utils import timezone
from rest_framework.authtoken.models import Token


#by convention you should use a singluar name for your class because it creates one instance
class ToDo(models.Model):
	text = models.CharField(max_length=250, unique=True)#unique makes it so that you can't repeat them
	timestamp = models.DateTimeField(default=datetime.now())
	completed = models.BooleanField(default=False)
	edited_date = models.DateTimeField(blank=True, null=True)

	def __str__(self):
		return self.text


	class Meta:
		ordering = ['completed', '-timestamp']

	def __str__(self):
		return self.text

	def save(self, *args, **kwargs):
		if not self.completed:
			self.edited_date = timezone.now()
		super(ToDo, self).save(*args, **kwargs)


# For newly created users
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

toDoSite/toDoApp/models.py
from django.db import models
from datetime import datetime

# Create your models here.

#by convention you should use a singluar name for your class because it creates one instance
class ToDo(models.Model):
    to_do_text = models.CharField(max_length=250, unique=True)#unique makes it so that you can't repeat them
    created_Date = models.DateTimeField(default=datetime.now())
    completed = models.BooleanField(default=False)
    # once you have set up a class you have to run a migrations with python \manage.py makemigrations doDoApp. Once this is successful you should have a 0001_initial in yoru omigrations folder. After any changes to models you must make another migration. this creates instructions for migrating. python manage.py migrate then actually migrates things to the app.

    def __str__(self):
        return self.to_do_text

toDoSite/rest_app/views.py
from django.shortcuts import render, get_object_or_404
from rest_framework import generics, viewsets, permissions
from .models import ToDo
from .serializers import ToDoSerializer


class TodoViewSet(viewsets.ModelViewSet):
    """
    API viewset for viewing todo instances.
    """
    queryset = ToDo.objects.all()
    serializer_class = ToDoSerializer

toDoSite/toDoApp/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required #import this for @login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from .models import ToDo
from django.urls import reverse

# Create your views here.


def index(request):
    to_do_list = ToDo.objects.all()
    context = {'to_do_list': to_do_list}
    return render(request, 'toDoApp/index.html', context)
    # return HttpResponse('ok. def index got called on the views page because urls.py at the app level has a path called views.index')

@login_required #makes it so that if the user isn;t logged in they get re-directed to the login page
def add(request):
    if request.method == 'POST':
        text = request.POST['to_do_text']
        ToDo(to_do_text=text).save()
    return HttpResponseRedirect(reverse('toDoApp:index'))


def delete(request, pk):
        # access the instance of ToDo class with the id of "id"
    # to_delete = ToDo.objects.filter(id=pk)
    get_object_or_404(ToDo, pk=pk).delete()
    # print(id)
    return HttpResponseRedirect(reverse('toDoApp:index'))


def mark_done(request, pk):
    to_do = get_object_or_404(ToDo, pk=pk)
    # to_do = ToDo.objects.get(pk=pk)
    to_do.completed = (not to_do.completed)
    to_do.save()
    # ToDo(to_do_text=f'you tried to mark item {pk} done.').save()
    return HttpResponseRedirect(reverse('toDoApp:index'))


def another(request):
    return HttpResponse('This is another_page')

toDoSite/toDoSite/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.http import HttpResponse


def register(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.clean_password2()
			user = authenticate(username=username, password=password)
			if user:
				login(request, user)
			return redirect('toDoApp:index')
		else:
			return HttpResponse('Invalid form')
	context = {'form': UserCreationForm()}
	return render(request, 'registration/register.html', context)

toDoSite/rest_app/templates/rest_app/todo_list_vue.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>To Do List</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'rest_app/style.css' %}">
    <script src="https://unpkg.com/vue@2.5.16/dist/vue.js"></script>
    <script src="https://unpkg.com/vue-resource@1.5.1/dist/vue-resource.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

  </head>


	<body>
	  <div id="app">
	          <h1>${heading}</h1>

	          <div class="holder">
	              <!-- Hint: modify this input to handle addTodo() -->
	              <input
	                type="text"
	                placeholder="Create note..."
	                v-on:keyup.enter="addToDo"
	                v-model="textForToDo"
	              />
								<div >
									<input id="search"
									type="text"
									placeholder="Search database..."
									v-on:keyup="search"
									v-model="query"
									/>
								</div>

								<ul>
										<li
										v-for="(x, index) in results"
										v-bind:class="{completed: x.completed}"
										v-bind:index="index"
										>
											${x.text}
											<button class="done" v-on:click="markDone(x.id, x.completed)">done</button>
											<!-- <button class="remove" v-on:click="removeToDo(x.id)">remove</button> -->
									</li>
								</ul>


	              <ul>
	                  <li
	                  v-for="(x, index) in toDos"
	                  v-bind:class="{completed: x.completed}"
	                  v-bind:index="index"
	                  >
	                    ${x.text}
	                    <button class="done" v-on:click="markDone(x.id, x.completed)">done</button>
	                    <button class="remove" v-on:click="removeToDo(x.id)">remove</button>
	                </li>
	              </ul>
	          </div>

	      </div>

	<script src="{% static 'rest_app/script.js' %}"></script>
	</body>

toDoSite/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>To Do</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">



  <!-- Add additional CSS in static file -->


  {% load static %}
  {% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{%static 'style.css' %}"/>
	{% endblock %}
	{% block extrastyles %}{% endblock %}
</head>

<body>
	{% block nav %}
	<nav>
		<ul class="sidebar-nav">
			<a href="{% url 'toDoApp:index' %}">Home</a></br>
			{% if user.is_authenticated %}
				<a href="{% url 'logout' %}">Logout</a></br>
			{% else %}
				<a href="{% url 'register' %}">Register</a></br>
				<a href="{% url 'login' %}">Login</a></br>
				{% endif %}
		</ul>
	</nav>
	{% endblock %}



    {% block sidebar %}{% endblock %}
<div class="content">
{% block content %}{% endblock %}
</div>

</body>
</html>

toDoSite/toDoApp/templates/toDoApp/index.html
{% extends "base_generic.html" %}
{% block content %}



<!DOCTYPE html>
<html>
<head>
  <title>TOOODODODOD!!!</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{%static 'toDoApp/style.css' %}"/>
</head>

<body>
  <div id="app">
    <h1>Do all these things:</h1>

    <div class="holder">
      <form action="{% url 'toDoApp:add' %}" method="post">
        {% csrf_token%}
        <input type="text" name="to_do_text" placeholder="item to add...">
        <button type="submit">+</button>
      </form>

      <ul>
        {% for item in to_do_list %}
        <li>
          <p
						{% if item.completed%}
            class="completed"
            {%endif%}>
            {{item.to_do_text}}
					</p>
					<form action="{% url 'toDoApp:delete' pk=item.id %}" method="post">
						<button type="submit" name="{{item.id}}">
							Remove
						</button>
						{% csrf_token%}
          </form>
          <a href="{% url 'toDoApp:mark_done' pk=item.id %}">Mark Done</a></button>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</body>
<html>


{% endblock content %}

toDoSite/toDoSite/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}To Do{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">



  <!-- Add additional CSS in static file -->


  {% load static %}
  {% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{%static 'style.css' %}"/>
	{% endblock %}
	{% block extrastyles %}{% endblock %}
</head>

<body>
	{% block nav %}
	<nav>
		<h1>To Do</h1>
		<ul class="sidebar-nav">
			<a href="{% url 'toDoApp:index.html' %}">Home</a></br>
			{% if user.is_authenticated %}
				<a href="{% url 'logout' %}">Logout</a></br>
			{% else %}
				<a href="{% url 'register' %}">Register</a></br>
				<a href="{% url 'login' %}">Login</a></br>
				{% endif %}
		</ul>
	</nav>
	{% endblock %}



    {% block sidebar %}{% endblock %}
<div class="content">
{% block content %}{% endblock %}
</div>

</body>
</html>